pac-server:
  build: .
  dockerfile: Dockerfile
  container_name: pac-server
  hostname: pac-server
  ports:
    - "3000:80/tcp"
  volumes:
    - "./pac.js:/var/spool/pac-server/pac.js"
  command:
    - "-maxage 3600"
  log_opt:
    max-size: "100k"
    max-file: "20"
